"""
ARDS Response Engine
====================

Executes the decision generated by the
Decision Engine.

This module performs security actions.
"""

import time


class ResponseEngine:

    def execute(self, decision):

        actions = []

        if decision["notify"]:

            actions.append("Dashboard Notification")

        if decision["quarantine"]:

            actions.append("Quarantine File")

        actions.append("Incident Logged")

        return {

            "timestamp": time.strftime("%H:%M:%S"),

            "behavior_id": decision["behavior_id"],

            "behavior_name": decision["behavior_name"],

            "risk_level": decision["risk_level"],

            "decision": decision["decision"],

            "actions": actions,

            "status": "Executed"

        }
    